parameters:
  selfupdate.phar_url: http://pitchart.github.io/gitlab-helper/gitlab-helper.phar
  selfupdate.version_url: http://pitchart.github.io/gitlab-helper/gitlab-helper.phar.version
services:
  http_client:
    class: 'GuzzleHttp\Client'
    arguments: [{'base_uri': '%gitlab.host%', 'headers': {'PRIVATE-TOKEN': '%gitlab.token%'}}]
  gitlab_client:
    class: Pitchart\GitlabHelper\Service\GitlabClient
    arguments: ['@http_client', '%gitlab.token%', '%gitlab.api_version%']