parameters:
  selfupdate.phar_url: 'https://pitchart.github.io/gitlab-helper/gitlab-helper.phar'
  selfupdate.version_url: 'https://pitchart.github.io/gitlab-helper/gitlab-helper.phar.version'
services:
  http_client:
    class: 'GuzzleHttp\Client'
    arguments: [{'base_uri': '%gitlab.host%', 'headers': {'PRIVATE-TOKEN': '%gitlab.token%'}}]
  gitlab_client:
    class: 'Pitchart\GitlabHelper\Service\GitlabClient'
    arguments: ['@http_client', '%gitlab.token%', '%gitlab.api_version%']
  gitlab_api_factory:
    class: 'Pitchart\GitlabHelper\Gitlab\Api\Factory'
    arguments: ['@gitlab_client']

  # APIs
  gitlab_api_group:
    class: 'Pitchart\GitlabHelper\Gitlab\Api\Group'
    arguments: ['@gitlab_client', 'groups']
    tags:
      - { name: 'gitlab_api', alias: 'group' }
  gitlab_api_project:
    class: 'Pitchart\GitlabHelper\Gitlab\Api\Project'
    arguments: ['@gitlab_client', 'projects']
    tags:
      - { name: 'gitlab_api', alias: 'project' }
  gitlab_api_user:
      class: 'Pitchart\GitlabHelper\Gitlab\Api\User'
      arguments: ['@gitlab_client', 'users']
      tags:
        - { name: 'gitlab_api', alias: 'user' }